name: hasco-deploy-dev

on: [push, workflow_dispatch]
jobs: 
  build-publish-and-deploy: # Job 
    name: Build and Publish # Job name
    runs-on: ubuntu-latest  # runs on ubuntu remote server
    
    steps: 
      # checkout action is used to clone the repo on the remote (ubuntu) server.
      - name: Clone the code on remote server
        uses: actions/checkout@v4
        # Instead of writing our own action below for cloning the repo on the remote server, we can use pre-built actions from github marketplace i.e. checkout action.
        # through the | multiple operations can be performed. github keyword is a reserved context which enquotes in a special syntax.
        # run: |  
        #   echo "cloning repo .."
        #   echo "${{toJson(github)}}"  
        #   git clone https://github.com/${{github.repository}}.git

      - name: Install Node.js v-20 
        uses: actions/setup-node@v4
        with: 
          node-version: 20
      - name: print node version
        run: node -v

      # Install the dependencies bc we have to run the test case via the vitest package. 
      # Rather than using the npm install use npm ci (clean install) main difference :- install will use the package.json file but npm ci will use the package-lock.json file which doesn't update our minor and patch version automatically we want exact version to be installed.
      - name: Install dependencies
        run: npm ci  # recommended way

      - name: Run test cases
        run: npm run test # test is the script which is in our packgae.json
      
  # Different job for deployement because we have to build version of the project. 
  deploy: # Job
    name: Deploy # Job name
    needs: build-publish-and-deploy  # If we want to run the jobs in a squential order so we can used the needs keyword and then pass the name of the first job.
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code on remote server for deployment
        uses: actions/checkout@v4

      - name: Install Node.js v-20
        uses: actions/setup-node@v4
        with: 
          node-version: 20

      - name: Install dependencies
        run: npm ci # recommended way instead of npm install

      - name: Build the project
        run: npm run build

      - name: Deploy the project 
        run:  |
         echo "Deploying the project ..."
         echo "Deployment successful..." 
        