name: hasco-test-dev

# on: push
on: workflow_dispatch
jobs: 
    build-publish-and-deploy: 
        name: Build and Publish
        runs-on: ubuntu-latest

        steps: 
            - name: "greet user"
              run: echo "Greeting from github actions to HasCo"