name: hasco-dev-cicd

on: push
jobs: 
    build-publish-and-deploy: 
        runs-on: ubuntu-latest
        steps: 
            - name: "greet user"
              run: echo "Greeting from github actions to HasCo"